# Generated by Django 3.0.5 on 2022-12-28 14:53

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clasificacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Consola',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Desarrolladora',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Juego',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('imagen', models.URLField(validators=[django.core.validators.URLValidator()])),
                ('url', models.URLField(validators=[django.core.validators.URLValidator()])),
                ('urlMetaReviews', models.URLField(validators=[django.core.validators.URLValidator()])),
                ('urlUsuariosReviews', models.URLField(validators=[django.core.validators.URLValidator()])),
                ('puntuacionMeta', models.IntegerField()),
                ('puntuacionUsuarios', models.FloatField()),
                ('fechaLanzamiento', models.DateField()),
                ('descripcion', models.CharField(max_length=200)),
                ('clasificacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Clasificacion')),
                ('consola', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Consola')),
                ('desarrolladoras', models.ManyToManyField(to='main.Desarrolladora')),
                ('generos', models.ManyToManyField(to='main.Genero')),
                ('otrasConsolas', models.ManyToManyField(related_name='otrasConsolas', to='main.Consola')),
            ],
        ),
    ]
